### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by davisidarta** [LTLA/BiocSingular#4]
Hello there BiocSingular Team!

I'm trying to install batchelor. However, when I run `devtools::install_github("LTLA/batchelor")`, I get the following error output:
```

Downloading GitHub repo LTLA/batchelor@master
Skipping 2 packages not available: BiocNeighbors, BiocSingular
Skipping 11 packages ahead of CRAN: beachmat, BiocGenerics, BiocParallel, DelayedArray, gtable, HDF5Array, IRanges, rhdf5, Rhdf5lib, rlang, S4Vectors
Installing 17 packages: Biobase, BiocSingular, DelayedMatrixStats, edgeR, GenomeInfoDb, GenomeInfoDbData, GenomicRanges, limma, locfit, rjson, scater, shinydashboard, SingleCellExperiment, SummarizedExperiment, tximport, XVector, zlibbioc
Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Error: (converted from warning) package ‘BiocSingular’ is not available (for R version 3.5.3)
```

**I've then tried to install biocSingular.** However, I get the following error:

```
In file included from /usr/local/lib/R/site-library/beachmat/include/beachmat/all_readers.h:4:0,
                 from /usr/local/lib/R/site-library/beachmat/include/beachmat/LIN_matrix.h:4,
                 from /usr/local/lib/R/site-library/beachmat/include/beachmat/numeric_matrix.h:4,
                 from compute_scale.cpp:2:
/usr/local/lib/R/site-library/beachmat/include/beachmat/beachmat.h:15:19: fatal error: H5Cpp.h: No such file or directory
 #include "H5Cpp.h"
                   ^
compilation terminated.
/usr/local/lib/R/etc/Makeconf:172: recipe for target 'compute_scale.o' failed
make: *** [compute_scale.o] Error 1
ERROR: compilation failed for package ‘BiocSingular’
* removing ‘/usr/local/lib/R/site-library/BiocSingular’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpGJQkfa/file1977a4d39ec/BiocSingular_0.99.14.tar.gz’ had non-zero exit status
```

Does anyone know a way to solve this? Any help will be really appreciated.

Thanks in advance!

Davi

**Comment by LTLA** [comment]
Install _BiocSingular_ as per the instructions on the Bioconductor landing page.

https://bioconductor.org/packages/devel/bioc/html/BiocSingular.html

It is worth keeping in mind that the Github repository is purely for the convenience of the developers. The canonical form of the package is always on Bioconductor, as noted in the description for this repository.

**Comment by davisidarta** [comment]
I've done that as well. There's an error message output:

Error: Bioconductor version '3.9' requires R version '3.6'; see https://bioconductor.org/install

However, R last build is 3.5.3. (https://cran.r-project.org/bin/windows/base/). How is someone supposed to install an unreleased build?

I'm very sorry if this is too basic. I've worked with bioinformatics for several months now, but it's my first time with BiocSingular.

Thank you in advance!

Best,

Davi

**Comment by LTLA** [comment]
https://www.r-project.org/, "Planting of a Tree".

**Comment by LTLA** [comment]
I'm going to assume this got fixed somewhere along the line.

**Comment by dongzhuoer** [comment]
still the same compilation error for `remotes::install_bioc('release/BiocSingular')`

**Comment by LTLA** [comment]
Session info?

**Comment by dongzhuoer** [comment]
Later I find that `BiocManager::install('BiocSingular')` succeeds, because it uses beachmat 2.0.0, while the former uses beachmat 1.4.0.

**Comment by dongzhuoer** [comment]
I think it's an issue of **remotes** package, and I will report there. Thank you anyway!

**Comment by brgew** [comment]
Hi @dongzhuoer,
Is this solved?
