### ISSUE TITLE
Travis complains: BiocSingular not available for R 3.6.0

### ISSUE THREAD

**Issue by mkarikom** [LTLA/BiocSingular#5]
See line 679 of the build log:
https://travis-ci.com/mkarikom/DummyPackage/jobs/206657498

**Comment by LTLA** [comment]
Looks like a Travis problem to me. It's all green here:

https://bioconductor.org/packages/release/bioc/html/BiocSingular.html

https://bioconductor.org/packages/devel/bioc/html/BiocSingular.html

... so everything's available from my end. Perhaps you have to use a BioC-aware deployment of R on Travis - I don't know the details.

**Comment by mkarikom** [comment]
Thanks, just posted to the R peeps at travis:
https://travis-ci.community/t/bioc-dep-not-available-for-r-3-6-its-available/3676

**Comment by LTLA** [comment]
Reopen this if it turns out to be my fault.
